# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-site',
                'doc_host': 'https://bahmanapl.github.io',
                'git_url': 'https://github.com/bahmanapl/nbdev-site',
                'lib_path': 'nbdev_site'},
  'syms': {'nbdev_site.core': {'nbdev_site.core.foo': ('core.html#foo', 'nbdev_site/core.py')}}}